"""update row_plan model

Revision ID: 07f10fdd41a3
Revises: 55e6818efa30
Create Date: 2025-06-05 18:45:52.516387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f10fdd41a3'
down_revision: Union[str, None] = '55e6818efa30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('row_plan', sa.Column('plan_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('row_plan', 'plan_time')
    # ### end Alembic commands ###
