"""add column or modify model

Revision ID: 091878c04ed1
Revises: 12f083429c3b
Create Date: 2025-07-24 13:38:39.644669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091878c04ed1'
down_revision: Union[str, None] = '12f083429c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('timer', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'end_time')
    op.drop_column('timer', 'start_time')
    # ### end Alembic commands ###
