"""Fix: add varchar length for MySQL

Revision ID: 4dad6fb1ec34
Revises: 
Create Date: 2025-04-07 13:15:35.218588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dad6fb1ec34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_plan_name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('unit_name', sa.String(length=30), nullable=False),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_row_plans_id'), 'row_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_row_plans_id'), table_name='row_plans')
    op.drop_table('row_plans')
    # ### end Alembic commands ###
