"""add all models

Revision ID: 9a58afae7bc3
Revises: 262b130e03b5
Create Date: 2025-05-25 10:20:47.537774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a58afae7bc3'
down_revision: Union[str, None] = '262b130e03b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_notes',
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.folder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pdf_id')
    )
    op.create_index(op.f('ix_pdf_notes_pdf_id'), 'pdf_notes', ['pdf_id'], unique=False)
    op.create_table('pdf_pages',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('page_order', sa.Integer(), nullable=True),
    sa.Column('image_preview_url', sa.Text(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_notes.pdf_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_pdf_pages_page_id'), 'pdf_pages', ['page_id'], unique=False)
    op.create_table('pdf_annotation',
    sa.Column('annotations_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('annotation_type', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pdf_pages.page_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotations_id')
    )
    op.create_index(op.f('ix_pdf_annotation_annotations_id'), 'pdf_annotation', ['annotations_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_annotation_annotations_id'), table_name='pdf_annotation')
    op.drop_table('pdf_annotation')
    op.drop_index(op.f('ix_pdf_pages_page_id'), table_name='pdf_pages')
    op.drop_table('pdf_pages')
    op.drop_index(op.f('ix_pdf_notes_pdf_id'), table_name='pdf_notes')
    op.drop_table('pdf_notes')
    # ### end Alembic commands ###
