"""Add new fields to timer

Revision ID: ce6b6f62037e
Revises: 1a123b27b7e6
Create Date: 2025-07-10 12:07:20.607665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6b6f62037e'
down_revision: Union[str, None] = '1a123b27b7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('timer', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'end_time')
    op.drop_column('timer', 'start_time')
    # ### end Alembic commands ###
