"""Add start_time and end_time to Timer

Revision ID: d6c72d2f711d
Revises: 07f10fdd41a3
Create Date: 2025-07-02 15:36:55.342719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c72d2f711d'
down_revision: Union[str, None] = '07f10fdd41a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('timer', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'end_time')
    op.drop_column('timer', 'start_time')
    # ### end Alembic commands ###
